### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by chenjiawei22** [mangonihao/MultiHeadJointEntityRelationExtraction_simple#1]
请问如何计算关系三元组的精确率,召回率,F1？

**Comment by mangonihao** [comment]
根据关系矩阵对应的两个实体的开始位置，是否分类正确计算

> 请问如何计算关系三元组的精确率,召回率,F1？

根据关系矩阵对应的两个实体的开始位置，是否分类正确计算

**Comment by Xie-Minghui** [comment]
> 请问如何计算关系三元组的精确率,召回率,F1？

根据关系矩阵对应的两个实体的开始位置，是否分类正确计算
